# Generated by Django 5.2.14 on 2026-05-19 16:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('odometer_km', models.PositiveIntegerField(help_text='Odometer reading when this service was done.')),
                ('title', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('diy', 'DIY'), ('shop', 'Shop')], default='diy', max_length=10)),
                ('shop_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-service_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('part', 'Part'), ('labor', 'Labor'), ('fee', 'Fee'), ('other', 'Other')], default='part', max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Price per unit in PHP.', max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, help_text='Computed: quantity × unit_cost.', max_digits=12)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='garage.maintenanceevent')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('vin', models.CharField(blank=True, max_length=50, verbose_name='VIN')),
                ('current_odometer_km', models.PositiveIntegerField(default=0, help_text='Latest known odometer reading in kilometers.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorcycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['brand', 'model', '-year'],
            },
        ),
        migrations.AddField(
            model_name='maintenanceevent',
            name='motorcycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_events', to='garage.motorcycle'),
        ),
    ]
